# Generated by Django 5.2.6 on 2026-01-08 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cores', '0002_accountingperiod'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MillingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], max_length=30)),
                ('batch_no', models.CharField(max_length=78, unique=True)),
                ('expiry_date', models.DateField()),
                ('premix_kg', models.FloatField(default=0)),
                ('maize_milled_kg', models.FloatField(default=0)),
                ('maize_germ_kg', models.FloatField(default=0)),
                ('maize_chaffs_kg', models.FloatField(default=0)),
                ('waste_kg', models.FloatField(default=0)),
                ('bales', models.PositiveIntegerField(default=0)),
                ('total_output_kg', models.FloatField(default=0, editable=False)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cores.branch')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cores.company')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
