# Generated by Django 5.2.6 on 2026-01-09 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='millingbatch',
            name='efficiency',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='millingbatch',
            name='batch_no',
            field=models.CharField(db_index=True, max_length=78, unique=True),
        ),
        migrations.AlterField(
            model_name='millingbatch',
            name='maize_chaffs_kg',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='millingbatch',
            name='maize_germ_kg',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='millingbatch',
            name='maize_milled_kg',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
