# Generated by Django 5.2.6 on 2025-12-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='model_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='new_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='old_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
