# Generated by Django 5.2.6 on 2026-01-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditt', '0002_auditlog_model_name_auditlog_new_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='object_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
