# Generated by Django 5.2.6 on 2025-11-24 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sale_quantity_alter_sale_total_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='productrecall',
            name='batch_number',
        ),
        migrations.AddField(
            model_name='productrecall',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recalls', to='sales.batch'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='batch_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='sales.batch'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='batch_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sales.batch'),
        ),
    ]
