# Generated by Django 5.2.6 on 2025-12-16 09:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_object_name_auditlog_model_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('administration', 'Administration'), ('field', 'Field'), ('warehousing', 'Warehousing'), ('transport', 'Transport')], default='field', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
    ]
