# Generated by Django 5.2.6 on 2025-12-22 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_deleted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
