# Generated by Django 5.2.6 on 2025-10-31 09:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('raw', 'Raw Material'), ('finished', 'Finished Product'), ('byproduct', 'By-product')], max_length=100)),
                ('unit', models.CharField(choices=[('kg', 'Kilograms'), ('pcs', 'pieces'), ('bag', 'Bags')], default='kg', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_raw_in', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_output', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_waste', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('efficiency_rate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='warehouse.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='DailyInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('raw_in', models.DecimalField(decimal_places=2, default=0, help_text='Raw material received/produced', max_digits=14)),
                ('shift_1', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('shift_2', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('shift_3', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_records', to='warehouse.material')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_inventory', to='warehouse.warehouse')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('warehouse', 'material', 'date')},
            },
        ),
    ]
