# Generated by Django 5.2.6 on 2025-11-06 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseanalytics',
            name='warehouse',
        ),
        migrations.AlterUniqueTogether(
            name='dailyinventory',
            unique_together={('material', 'date')},
        ),
        migrations.RemoveField(
            model_name='dailyinventory',
            name='warehouse',
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
