# Generated by Django 5.2.6 on 2025-11-12 05:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_remove_warehouseanalytics_warehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyinventory',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyinventory',
            name='total_shift_output',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='dailyinventory',
            name='variance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('pcs', 'Pieces'), ('bag', 'Bags')], default='kg', max_length=10),
        ),
        migrations.AlterField(
            model_name='warehouseanalytics',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, unique=True),
        ),
    ]
