# Generated by Django 5.2.6 on 2025-11-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_dailyinventory_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.CharField(choices=[('raw_material', 'Raw Material'), ('final_product', 'Final Product'), ('by_product', 'By-Product'), ('stock_in_store', 'Stock in Store'), ('unknown', 'Unknown')], max_length=100),
        ),
    ]
