# Generated by Django 5.2.6 on 2025-11-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_alter_material_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.CharField(choices=[('raw_material', 'Raw Material'), ('final_product', 'Final Product'), ('by_product', 'By-Product'), ('stock_out', 'Stock out'), ('Balance_In_Store', 'Balance In Store')], max_length=100),
        ),
    ]
