# Generated by Django 5.2.6 on 2025-11-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_alter_material_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('name', 'category')},
        ),
    ]
