# Generated by Django 5.2.6 on 2025-12-31 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cores', '0002_accountingperiod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interval', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=23)),
                ('max_users', models.PositiveIntegerField()),
                ('max_branches', models.PositiveIntegerField()),
                ('enable_transport', models.BooleanField(default=True)),
                ('enable_warehouse', models.BooleanField(default=True)),
                ('enable_sales', models.BooleanField(default=True)),
                ('enable_marketing', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past_due'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('grace_period_days', models.PositiveIntegerField(default=7)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cores.company')),
            ],
        ),
    ]
