# Generated by Django 5.2.6 on 2025-10-23 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plate_number', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('lorry', 'Lorry'), ('probox', 'Probox'), ('landcruiser', 'landcruiser')], default='probox', max_length=50)),
                ('driver_name', models.CharField(max_length=60)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['plate_number'],
            },
        ),
        migrations.CreateModel(
            name='TransportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fuel_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('logistics_cost', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('mechanical_issues', models.TextField(blank=True, null=True)),
                ('action_taken', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='transport.vehicle')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('vehicle', 'date')},
            },
        ),
    ]
