# Generated by Django 5.2.6 on 2025-10-24 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportrecord',
            name='action_taken',
        ),
        migrations.RemoveField(
            model_name='transportrecord',
            name='logistics_cost',
        ),
    ]
