# Generated by Django 5.2.6 on 2025-11-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_remove_transportrecord_action_taken_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transportrecord',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='category',
            field=models.CharField(choices=[('lorry', 'Lorry'), ('probox', 'Probox'), ('landcruiser', 'Land Cruiser')], default='probox', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='transportrecord',
            constraint=models.UniqueConstraint(fields=('vehicle', 'date'), name='unique_vehicle_date'),
        ),
    ]
