# Generated by Django 5.2.6 on 2025-10-15 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlourOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening'), ('night', 'Night')], max_length=20)),
                ('product_name', models.CharField(default='NACONEK CSB 25KG', max_length=100)),
                ('total_bags', models.IntegerField(default=0)),
                ('spillage_kg', models.FloatField(default=0)),
                ('germ_kg', models.FloatField(default=0)),
                ('chaff_kg', models.FloatField(default=0)),
                ('waste_kg', models.FloatField(default=0)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening'), ('night', 'Night')], max_length=20)),
                ('maize_kg', models.FloatField(default=0)),
                ('soya_kg', models.FloatField(default=0)),
                ('sugar_kg', models.FloatField(default=0)),
                ('sorghum_kg', models.FloatField(default=0)),
                ('premix_kg', models.FloatField(default=0)),
                ('total_raw_material', models.FloatField(default=0)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
