# Generated by Django 5.2.6 on 2025-10-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flouroutput',
            name='efficiency',
            field=models.FloatField(default=0),
        ),
    ]
