# Generated by Django 5.2.6 on 2025-10-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_flouroutput_efficiency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flouroutput',
            name='efficiency',
        ),
        migrations.AddField(
            model_name='flouroutput',
            name='efficiency_rate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
