# Generated by Django 5.2.6 on 2025-10-22 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_remove_flouroutput_efficiency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flouroutput',
            old_name='efficiency_rate',
            new_name='efficiency',
        ),
    ]
