# Generated by Django 5.2.6 on 2025-12-29 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0001_initial'),
        ('production', '0004_rename_efficiency_rate_flouroutput_efficiency'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cores.branch'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cores.company'),
        ),
    ]
